### PR TITLE
Add support for PHP 7.4

### PR DESCRIPTION
**Pull request by owenvoke**
This updates Larasail to use PHP 7.4 as the default version of PHP. It also adds an additional argument (`php73`) for installing PHP 7.3.

### CODE REVIEW

**Comment by wimurk** [comment]
+1

**Comment by butaminas** [comment]
Doesn't work for me. Still installs PHP 7.2.

**Comment by wimurk** [comment]
@pxgamer set it as default. 7.4 is already on the way.

**Comment by pxgamer** [comment]
@butaminas, are you installing from my fork (and branch)? Or the main repository? :thinking:

This PR hasn't been merged so the official Larasail won't use PHP 7.3 yet.

**Comment by butaminas** [comment]
> @butaminas, are you installing from my fork (and branch)? Or the main repository? 🤔
> 
> This PR hasn't been merged so the official Larasail won't use PHP 7.3 yet.

It's weird, because I've installed it from your branch. I've seen few times it was doing something with php 7.3 but most of the time it was installing and configuring 7.2. After the installation I did `php -v` and it was 7.2.

I have now upgraded to php 7.3 manually.

I was using Ubuntu 16.04.

**Comment by wimurk** [comment]
@pxgamer yes i know. i use the main. But you asked if it would be a good idea to set is as default or as option. I suggest you set it as default. And add 7.4 in a new PR. :-)

**Comment by pxgamer** [comment]
I've tested on a clean droplet (Ubuntu 18.04) and it installed PHP 7.3 as expected. 🤔
```bash
curl -sL https://github.com/pxgamer/larasail/archive/feature/php-7.3.tar.gz | tar xz && source larasail-feature-php-7.3/install
```

Console output preview

**Comment by butaminas** [comment]
@pxgamer strange. Could it be the 16.04? Or perhaps I messed it up somehow.

Yeah, the project seems to be dead, though it is still an awesome tool. Thanks for trying to keep it alive.

**Comment by wimurk** [comment]
It looks dead indeed. Maybe someone can fork the project and keep it maintained?

**Comment by owenvoke** [comment]
@bobbyiliev, if we're going to add this, would it be better to just change this to use PHP 7.4 by default, and add `php73` as an argument? And I'll add the APT repository 👍

**Comment by bobbyiliev** [comment]
@owenvoke  Yes that is a good point, I think that PHP 7.4 sounds good, this would also close the #23 issue.

**Comment by owenvoke** [comment]
@bobbyiliev, I've updated this to use PHP 7.4 by default with a `php73` argument available.

Looking at https://github.com/thedevdojo/larasail/blob/ed5a2399420fc0e5ae84e1af17e849211d6dfed3/.larasail/setup#L72-L75, it appears to already setup the `ondrej/php` repository so I don't think any changes need to be applied on that front?

**Pull request merged**
