### PR TITLE
Feature: Wave Support

### LINKED ISSUE #63: Feature: Install Laravel Wave
### Is your feature request related to a problem? Please describe.

As [Laravel Wave](https://github.com/thedevdojo/wave) is no opensource, it would be nice to have an option to install it via LaraSail.

### Describe the solution you'd like

Add an argument to allow Laravel Wave installation rather than plain Laravel installation.

### PR DESCRIPTION
**Pull request by SamuelMwangiW**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Adds support for creating a project from the open source wave instead of the default blank copy of Laravel

## Related Tickets & Documents

Closes #63 

## Added to documentation?
- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by SamuelMwangiW** [comment]
Tested to work in `mysql`, pending test with recently added `MariaDB`.

This is still much a work in progress and has some rough edges that may need further working on.

Composer install is failing if DB connection details are incorrect hence hooked onto `larasail database init` to setup DB during setup (this more of a workaround than intended behavior given existing laravel workflow)

Extracted `Laravel` and `Wave` installations to separate files to avoid cluttering `.larasail/new` and make it extensible in future.

@bobbyiliev Kindly give a test drive and let me have your initial thoughts `larasail new wave.test --wave`. (Will update the readme shortly with howto later on tomorrow)

**Review by bobbyiliev — COMMENTED** [review]
Looks good! Thank you for your contribution! I will do some testing later on this week and merge this!

**Comment by SamuelMwangiW** [comment]
Thanks @bobbyiliev. Let me know your thoughts once you test. I've been held up lately haven't updated the README but will try and do that over the weekend

**Comment by SamuelMwangiW** [comment]
@bobbyiliev am unable to convert the PR into draft mode. Needs a bit more testing, kindly pause merging it

**Review by bobbyiliev — APPROVED** [review]
This is great! Thank you for the great contribution! 🚀

**Comment by bobbyiliev** [comment]
Hey @SamuelMwangiW missed your last comment and had to revert that one. Feel free to open a new PR with the latest changes!

**Comment by SamuelMwangiW** [comment]
Hey @bobbyiliev. Thanks a lot for reviewing and merging the PRs. I had made the request after encountering issues with MariaDB (#68 and #70) that I wanted merged first

**Pull request merged**
